[target.x86_64-yeetos]
rustflags = [
    "-Csoft-float",
    "-Clink-arg=--entry=kernel_main",
    "-Clink-arg=--image-base=0xfffff00002000000",
    
]

[target.i686-yeetos]
rustflags = [
    "-Csoft-float",
    "-Clink-arg=--entry=kernel_main",
    "-Clink-arg=--image-base=0xC2000000",

]

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]
