[target.x86_64-yeetos]
rustflags = ["-Csoft-float", "-Clink-args=--script=linkers/x86_64.ld" ]

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc" ]
